// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: rebuildstack/ingest/kubernetes/v1/collection_coverage.proto

// The `collection_coverage` payload: what the agent did, not what it found.

package kubernetesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// What the agent looked at, what it was configured to skip and under which
// control, which of its reads worked, and the shape of the configuration in
// force. Its subject is the agent itself, which is what separates it from every
// other payload kind.
//
// Every number here is an aggregate. No name of an excluded, dropped or
// refused object appears anywhere in this message.
type CollectionCoverage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The payload kind: "collection_coverage".
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// The class of claim these facts are: "agent" — a fact about the collection
	// rather than about the cluster.
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// When this report was assembled. It is written on every flush whether or not
	// anything changed, so a captured_at that stops advancing is a fact about the
	// agent where silence in any other kind is not.
	CapturedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"`
	// The base of every cumulative counter below: when this agent process began
	// counting. A counter that fell rather than rose means the process restarted,
	// which a moved `since` is what shows.
	Since *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=since,proto3" json:"since,omitempty"`
	// What the agent is and how it is configured.
	Agent *AgentInfo `protobuf:"bytes,5,opt,name=agent,proto3" json:"agent,omitempty"`
	// Each watched source as the agent found it: read access as measured, rather
	// than as granted.
	Sources []*SourceHealth `protobuf:"bytes,6,rep,name=sources,proto3" json:"sources,omitempty"`
	// What the pod and Job filters admitted and excluded.
	Filter *FilterCoverage `protobuf:"bytes,7,opt,name=filter,proto3" json:"filter,omitempty"`
	// What the placement reduction refused to carry from collected workloads.
	Placement *PlacementDrops `protobuf:"bytes,8,opt,name=placement,proto3" json:"placement,omitempty"`
	// What the node reductions refused to carry from collected nodes.
	Nodes *NodeDrops `protobuf:"bytes,9,opt,name=nodes,proto3" json:"nodes,omitempty"`
	// The Go inventory's state, and what the on-node process scans did. Both are
	// present only when the on-node role is deployed.
	Inventory *InventoryCounters `protobuf:"bytes,10,opt,name=inventory,proto3" json:"inventory,omitempty"`
	Scan      *ScanCoverage      `protobuf:"bytes,11,opt,name=scan,proto3" json:"scan,omitempty"`
	// What the on-node profilers did. Present once a node has reported it.
	Ebpf *ProfileCoverage `protobuf:"bytes,12,opt,name=ebpf,proto3" json:"ebpf,omitempty"`
	// Workload targets by the latest answer about their profiling endpoint.
	// Present only when endpoint discovery is enabled.
	Pprof *PprofCoverage `protobuf:"bytes,13,opt,name=pprof,proto3" json:"pprof,omitempty"`
	// What the agent's receiver for on-node reports refused. Present only when
	// that receiver is enabled.
	IntakeRejections *IntakeRejections `protobuf:"bytes,14,opt,name=intake_rejections,json=intakeRejections,proto3" json:"intake_rejections,omitempty"`
	// What fetching profiles from confirmed endpoints did. Present only when
	// profiles are pulled.
	PprofPull     *PprofPullCoverage `protobuf:"bytes,15,opt,name=pprof_pull,json=pprofPull,proto3" json:"pprof_pull,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionCoverage) Reset() {
	*x = CollectionCoverage{}
	mi := &file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionCoverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionCoverage) ProtoMessage() {}

func (x *CollectionCoverage) ProtoReflect() protoreflect.Message {
	mi := &file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionCoverage.ProtoReflect.Descriptor instead.
func (*CollectionCoverage) Descriptor() ([]byte, []int) {
	return file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_rawDescGZIP(), []int{0}
}

func (x *CollectionCoverage) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CollectionCoverage) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CollectionCoverage) GetCapturedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CapturedAt
	}
	return nil
}

func (x *CollectionCoverage) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *CollectionCoverage) GetAgent() *AgentInfo {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *CollectionCoverage) GetSources() []*SourceHealth {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *CollectionCoverage) GetFilter() *FilterCoverage {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *CollectionCoverage) GetPlacement() *PlacementDrops {
	if x != nil {
		return x.Placement
	}
	return nil
}

func (x *CollectionCoverage) GetNodes() *NodeDrops {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *CollectionCoverage) GetInventory() *InventoryCounters {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *CollectionCoverage) GetScan() *ScanCoverage {
	if x != nil {
		return x.Scan
	}
	return nil
}

func (x *CollectionCoverage) GetEbpf() *ProfileCoverage {
	if x != nil {
		return x.Ebpf
	}
	return nil
}

func (x *CollectionCoverage) GetPprof() *PprofCoverage {
	if x != nil {
		return x.Pprof
	}
	return nil
}

func (x *CollectionCoverage) GetIntakeRejections() *IntakeRejections {
	if x != nil {
		return x.IntakeRejections
	}
	return nil
}

func (x *CollectionCoverage) GetPprofPull() *PprofPullCoverage {
	if x != nil {
		return x.PprofPull
	}
	return nil
}

// What the agent is and how it is set up, so a reader knows what the counts
// beside it rest on.
type AgentInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The agent build. "dev" means an unstamped binary.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// The shape of the configuration in force.
	Config *ConfigShape `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	// Which kubelet signals this cluster exposes, e.g. "cpu", "memory",
	// "network", "throttling". Empty means the agent found none.
	UsageSignals  []string `protobuf:"bytes,3,rep,name=usage_signals,json=usageSignals,proto3" json:"usage_signals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_rawDescGZIP(), []int{1}
}

func (x *AgentInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentInfo) GetConfig() *ConfigShape {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *AgentInfo) GetUsageSignals() []string {
	if x != nil {
		return x.UsageSignals
	}
	return nil
}

// The shape of the agent's configuration: how many entries each filter list
// holds, and which switches are on.
//
// It carries no entry from any list — no namespace name, no module prefix, and
// no hash of either, since a digest of a handful of short names is reversible
// by trying the plausible ones.
type ConfigShape struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When the configuration in force took effect.
	Since *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=since,proto3" json:"since,omitempty"`
	// How many entries the namespace allow and deny lists hold. An empty allow
	// list admits every namespace, so zero and three are different postures
	// rather than more and less of one. Absent means the count was not stated.
	NamespacesAllowed *int64 `protobuf:"varint,2,opt,name=namespaces_allowed,json=namespacesAllowed,proto3,oneof" json:"namespaces_allowed,omitempty"`
	NamespacesDenied  *int64 `protobuf:"varint,3,opt,name=namespaces_denied,json=namespacesDenied,proto3,oneof" json:"namespaces_denied,omitempty"`
	// Whether profiling is enabled at all. Absent means the switch was not
	// stated; false is a claim that it is off.
	ProfilingEnabled *bool `protobuf:"varint,4,opt,name=profiling_enabled,json=profilingEnabled,proto3,oneof" json:"profiling_enabled,omitempty"`
	// How many workloads a profiling answer may name. Absent when no such limit
	// is configured.
	ProfilingTopN int64 `protobuf:"varint,5,opt,name=profiling_top_n,json=profilingTopN,proto3" json:"profiling_top_n,omitempty"`
	// Whether the agent may connect to a collected workload to confirm a
	// profiling endpoint, and whether it may then fetch a profile from one.
	// Absent means the switch was not stated; false is a claim that it is off.
	PprofDiscoveryEnabled *bool `protobuf:"varint,6,opt,name=pprof_discovery_enabled,json=pprofDiscoveryEnabled,proto3,oneof" json:"pprof_discovery_enabled,omitempty"`
	PprofPullEnabled      *bool `protobuf:"varint,7,opt,name=pprof_pull_enabled,json=pprofPullEnabled,proto3,oneof" json:"pprof_pull_enabled,omitempty"`
	// How many module prefixes the operator added to the symbol allow-list. A
	// count, never a prefix. Absent means the count was not stated.
	SymbolPrefixesAllowed *int64 `protobuf:"varint,8,opt,name=symbol_prefixes_allowed,json=symbolPrefixesAllowed,proto3,oneof" json:"symbol_prefixes_allowed,omitempty"`
	// Whether the receiver for on-node reports is open. Absent means the switch
	// was not stated; false is a claim that it is closed.
	NodeIntakeEnabled *bool `protobuf:"varint,9,opt,name=node_intake_enabled,json=nodeIntakeEnabled,proto3,oneof" json:"node_intake_enabled,omitempty"`
	// How many hours an unacknowledged payload may wait locally before it is
	// dropped. Absent when the agent's own built-in bound is what applies.
	SpoolMaxAgeHours int64 `protobuf:"varint,10,opt,name=spool_max_age_hours,json=spoolMaxAgeHours,proto3" json:"spool_max_age_hours,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfigShape) Reset() {
	*x = ConfigShape{}
	mi := &file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigShape) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigShape) ProtoMessage() {}

func (x *ConfigShape) ProtoReflect() protoreflect.Message {
	mi := &file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigShape.ProtoReflect.Descriptor instead.
func (*ConfigShape) Descriptor() ([]byte, []int) {
	return file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigShape) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *ConfigShape) GetNamespacesAllowed() int64 {
	if x != nil && x.NamespacesAllowed != nil {
		return *x.NamespacesAllowed
	}
	return 0
}

func (x *ConfigShape) GetNamespacesDenied() int64 {
	if x != nil && x.NamespacesDenied != nil {
		return *x.NamespacesDenied
	}
	return 0
}

func (x *ConfigShape) GetProfilingEnabled() bool {
	if x != nil && x.ProfilingEnabled != nil {
		return *x.ProfilingEnabled
	}
	return false
}

func (x *ConfigShape) GetProfilingTopN() int64 {
	if x != nil {
		return x.ProfilingTopN
	}
	return 0
}

func (x *ConfigShape) GetPprofDiscoveryEnabled() bool {
	if x != nil && x.PprofDiscoveryEnabled != nil {
		return *x.PprofDiscoveryEnabled
	}
	return false
}

func (x *ConfigShape) GetPprofPullEnabled() bool {
	if x != nil && x.PprofPullEnabled != nil {
		return *x.PprofPullEnabled
	}
	return false
}

func (x *ConfigShape) GetSymbolPrefixesAllowed() int64 {
	if x != nil && x.SymbolPrefixesAllowed != nil {
		return *x.SymbolPrefixesAllowed
	}
	return 0
}

func (x *ConfigShape) GetNodeIntakeEnabled() bool {
	if x != nil && x.NodeIntakeEnabled != nil {
		return *x.NodeIntakeEnabled
	}
	return false
}

func (x *ConfigShape) GetSpoolMaxAgeHours() int64 {
	if x != nil {
		return x.SpoolMaxAgeHours
	}
	return 0
}

// One watched source as the agent found it.
type SourceHealth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource class watched, e.g. "services", "endpoint_slices". Never the
	// name of an object in the cluster.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Whether the agent's cache of that source ever filled. Absent means it was
	// not stated; false is a claim that the cache never filled.
	Synced *bool `protobuf:"varint,2,opt,name=synced,proto3,oneof" json:"synced,omitempty"`
	// Whether the watch has been failing recently enough to treat the cache as no
	// longer fed. Absent means it was not stated; false is a claim that the cache
	// is still being fed.
	Failing       *bool `protobuf:"varint,3,opt,name=failing,proto3,oneof" json:"failing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceHealth) Reset() {
	*x = SourceHealth{}
	mi := &file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceHealth) ProtoMessage() {}

func (x *SourceHealth) ProtoReflect() protoreflect.Message {
	mi := &file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceHealth.ProtoReflect.Descriptor instead.
func (*SourceHealth) Descriptor() ([]byte, []int) {
	return file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_rawDescGZIP(), []int{3}
}

func (x *SourceHealth) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SourceHealth) GetSynced() bool {
	if x != nil && x.Synced != nil {
		return *x.Synced
	}
	return false
}

func (x *SourceHealth) GetFailing() bool {
	if x != nil && x.Failing != nil {
		return *x.Failing
	}
	return false
}

// How many pods and Jobs the filter looked at and excluded, counted once per
// appearance, and under which control.
//
// Counts only: the identity of an excluded object never appears. Absent means
// the counter was not stated; zero is a claim that nothing was excluded under
// that control.
type FilterCoverage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Every pod the filter looked at.
	PodsObserved *int64 `protobuf:"varint,1,opt,name=pods_observed,json=podsObserved,proto3,oneof" json:"pods_observed,omitempty"`
	// Pods excluded by the configured namespace lists.
	ExcludedNamespaceFilter *int64 `protobuf:"varint,2,opt,name=excluded_namespace_filter,json=excludedNamespaceFilter,proto3,oneof" json:"excluded_namespace_filter,omitempty"`
	// Pods excluded by an opt-out annotation, by the object that carried it.
	ExcludedNamespaceAnnotation *int64 `protobuf:"varint,3,opt,name=excluded_namespace_annotation,json=excludedNamespaceAnnotation,proto3,oneof" json:"excluded_namespace_annotation,omitempty"`
	ExcludedWorkloadAnnotation  *int64 `protobuf:"varint,4,opt,name=excluded_workload_annotation,json=excludedWorkloadAnnotation,proto3,oneof" json:"excluded_workload_annotation,omitempty"`
	ExcludedPodAnnotation       *int64 `protobuf:"varint,5,opt,name=excluded_pod_annotation,json=excludedPodAnnotation,proto3,oneof" json:"excluded_pod_annotation,omitempty"`
	// Pods that were collected and not profiled: the opt-out that removes a
	// workload from profiling while leaving everything else about it collected.
	ExcludedProfilingAnnotation *int64 `protobuf:"varint,6,opt,name=excluded_profiling_annotation,json=excludedProfilingAnnotation,proto3,oneof" json:"excluded_profiling_annotation,omitempty"`
	// Pods admitted without their workload's opt-out being checked: the workload
	// is of a kind the agent does not read, or it was not in the agent's cache.
	// They are separate counters because the first is a standing property of a
	// cluster and the second is not.
	WorkloadUnknownKind *int64 `protobuf:"varint,7,opt,name=workload_unknown_kind,json=workloadUnknownKind,proto3,oneof" json:"workload_unknown_kind,omitempty"`
	WorkloadNotCached   *int64 `protobuf:"varint,8,opt,name=workload_not_cached,json=workloadNotCached,proto3,oneof" json:"workload_not_cached,omitempty"`
	// Every Job the filter looked at.
	//
	// The Job counters are kept apart from the pod ones because one Job produces
	// many pods, and a shared counter would answer neither question.
	JobsObserved *int64 `protobuf:"varint,9,opt,name=jobs_observed,json=jobsObserved,proto3,oneof" json:"jobs_observed,omitempty"`
	// Jobs excluded by the configured namespace lists.
	JobsExcludedNamespaceFilter *int64 `protobuf:"varint,10,opt,name=jobs_excluded_namespace_filter,json=jobsExcludedNamespaceFilter,proto3,oneof" json:"jobs_excluded_namespace_filter,omitempty"`
	// Jobs excluded by an opt-out annotation on the namespace, on the workload
	// that owns the Job, and on the Job itself.
	JobsExcludedNamespaceAnnotation *int64 `protobuf:"varint,11,opt,name=jobs_excluded_namespace_annotation,json=jobsExcludedNamespaceAnnotation,proto3,oneof" json:"jobs_excluded_namespace_annotation,omitempty"`
	JobsExcludedWorkloadAnnotation  *int64 `protobuf:"varint,12,opt,name=jobs_excluded_workload_annotation,json=jobsExcludedWorkloadAnnotation,proto3,oneof" json:"jobs_excluded_workload_annotation,omitempty"`
	JobsExcludedAnnotation          *int64 `protobuf:"varint,13,opt,name=jobs_excluded_annotation,json=jobsExcludedAnnotation,proto3,oneof" json:"jobs_excluded_annotation,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *FilterCoverage) Reset() {
	*x = FilterCoverage{}
	mi := &file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterCoverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterCoverage) ProtoMessage() {}

func (x *FilterCoverage) ProtoReflect() protoreflect.Message {
	mi := &file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterCoverage.ProtoReflect.Descriptor instead.
func (*FilterCoverage) Descriptor() ([]byte, []int) {
	return file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_rawDescGZIP(), []int{4}
}

func (x *FilterCoverage) GetPodsObserved() int64 {
	if x != nil && x.PodsObserved != nil {
		return *x.PodsObserved
	}
	return 0
}

func (x *FilterCoverage) GetExcludedNamespaceFilter() int64 {
	if x != nil && x.ExcludedNamespaceFilter != nil {
		return *x.ExcludedNamespaceFilter
	}
	return 0
}

func (x *FilterCoverage) GetExcludedNamespaceAnnotation() int64 {
	if x != nil && x.ExcludedNamespaceAnnotation != nil {
		return *x.ExcludedNamespaceAnnotation
	}
	return 0
}

func (x *FilterCoverage) GetExcludedWorkloadAnnotation() int64 {
	if x != nil && x.ExcludedWorkloadAnnotation != nil {
		return *x.ExcludedWorkloadAnnotation
	}
	return 0
}

func (x *FilterCoverage) GetExcludedPodAnnotation() int64 {
	if x != nil && x.ExcludedPodAnnotation != nil {
		return *x.ExcludedPodAnnotation
	}
	return 0
}

func (x *FilterCoverage) GetExcludedProfilingAnnotation() int64 {
	if x != nil && x.ExcludedProfilingAnnotation != nil {
		return *x.ExcludedProfilingAnnotation
	}
	return 0
}

func (x *FilterCoverage) GetWorkloadUnknownKind() int64 {
	if x != nil && x.WorkloadUnknownKind != nil {
		return *x.WorkloadUnknownKind
	}
	return 0
}

func (x *FilterCoverage) GetWorkloadNotCached() int64 {
	if x != nil && x.WorkloadNotCached != nil {
		return *x.WorkloadNotCached
	}
	return 0
}

func (x *FilterCoverage) GetJobsObserved() int64 {
	if x != nil && x.JobsObserved != nil {
		return *x.JobsObserved
	}
	return 0
}

func (x *FilterCoverage) GetJobsExcludedNamespaceFilter() int64 {
	if x != nil && x.JobsExcludedNamespaceFilter != nil {
		return *x.JobsExcludedNamespaceFilter
	}
	return 0
}

func (x *FilterCoverage) GetJobsExcludedNamespaceAnnotation() int64 {
	if x != nil && x.JobsExcludedNamespaceAnnotation != nil {
		return *x.JobsExcludedNamespaceAnnotation
	}
	return 0
}

func (x *FilterCoverage) GetJobsExcludedWorkloadAnnotation() int64 {
	if x != nil && x.JobsExcludedWorkloadAnnotation != nil {
		return *x.JobsExcludedWorkloadAnnotation
	}
	return 0
}

func (x *FilterCoverage) GetJobsExcludedAnnotation() int64 {
	if x != nil && x.JobsExcludedAnnotation != nil {
		return *x.JobsExcludedAnnotation
	}
	return 0
}

// What the placement reduction refused to carry from a workload's scheduling
// constraints. The workload is collected; part of what its manifest states is
// not represented.
//
// Absent means the counter was not stated; zero is a claim that nothing was
// dropped.
type PlacementDrops struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Terms dropped because an operator-written string in them was over the
	// length this schema carries; the term is dropped rather than truncated.
	ValuesDropped *int64 `protobuf:"varint,1,opt,name=values_dropped,json=valuesDropped,proto3,oneof" json:"values_dropped,omitempty"`
	// Terms dropped past the bound on how many of one kind are carried from one
	// pod.
	TermsDropped  *int64 `protobuf:"varint,2,opt,name=terms_dropped,json=termsDropped,proto3,oneof" json:"terms_dropped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlacementDrops) Reset() {
	*x = PlacementDrops{}
	mi := &file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacementDrops) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacementDrops) ProtoMessage() {}

func (x *PlacementDrops) ProtoReflect() protoreflect.Message {
	mi := &file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacementDrops.ProtoReflect.Descriptor instead.
func (*PlacementDrops) Descriptor() ([]byte, []int) {
	return file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_rawDescGZIP(), []int{5}
}

func (x *PlacementDrops) GetValuesDropped() int64 {
	if x != nil && x.ValuesDropped != nil {
		return *x.ValuesDropped
	}
	return 0
}

func (x *PlacementDrops) GetTermsDropped() int64 {
	if x != nil && x.TermsDropped != nil {
		return *x.TermsDropped
	}
	return 0
}

// What the node reductions refused to carry, cumulative since the agent
// started. The node is collected; part of what it reports is not represented.
//
// Absent means the counter was not stated; zero is a claim that nothing was
// dropped.
type NodeDrops struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Conditions dropped for being of a type this schema does not carry.
	ConditionsDropped *int64 `protobuf:"varint,1,opt,name=conditions_dropped,json=conditionsDropped,proto3,oneof" json:"conditions_dropped,omitempty"`
	// Extended resources dropped for their vendor prefix, or past the bound on
	// how many are carried from one node.
	DevicesDropped *int64 `protobuf:"varint,2,opt,name=devices_dropped,json=devicesDropped,proto3,oneof" json:"devices_dropped,omitempty"`
	// Taints dropped for a key or value over the length this schema carries, or
	// past the same bound.
	TaintsDropped *int64 `protobuf:"varint,3,opt,name=taints_dropped,json=taintsDropped,proto3,oneof" json:"taints_dropped,omitempty"`
	// Single values dropped for their length, where the record around them was
	// kept — a condition reason, and the scalar fields of a node.
	ValuesDropped *int64 `protobuf:"varint,4,opt,name=values_dropped,json=valuesDropped,proto3,oneof" json:"values_dropped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeDrops) Reset() {
	*x = NodeDrops{}
	mi := &file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDrops) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDrops) ProtoMessage() {}

func (x *NodeDrops) ProtoReflect() protoreflect.Message {
	mi := &file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDrops.ProtoReflect.Descriptor instead.
func (*NodeDrops) Descriptor() ([]byte, []int) {
	return file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_rawDescGZIP(), []int{6}
}

func (x *NodeDrops) GetConditionsDropped() int64 {
	if x != nil && x.ConditionsDropped != nil {
		return *x.ConditionsDropped
	}
	return 0
}

func (x *NodeDrops) GetDevicesDropped() int64 {
	if x != nil && x.DevicesDropped != nil {
		return *x.DevicesDropped
	}
	return 0
}

func (x *NodeDrops) GetTaintsDropped() int64 {
	if x != nil && x.TaintsDropped != nil {
		return *x.TaintsDropped
	}
	return 0
}

func (x *NodeDrops) GetValuesDropped() int64 {
	if x != nil && x.ValuesDropped != nil {
		return *x.ValuesDropped
	}
	return 0
}

// The state of the cluster's Go inventory, and how much of what nodes sent
// joined to a workload.
//
// Absent means the counter was not stated; zero is a number that was counted.
type InventoryCounters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Distinct (namespace, workload, container) records currently held.
	Records *int64 `protobuf:"varint,1,opt,name=records,proto3,oneof" json:"records,omitempty"`
	// Distinct Go versions across those records.
	GoVersions *int64 `protobuf:"varint,2,opt,name=go_versions,json=goVersions,proto3,oneof" json:"go_versions,omitempty"`
	// How many of those records were built with profile-guided optimization.
	PgoBuilds *int64 `protobuf:"varint,3,opt,name=pgo_builds,json=pgoBuilds,proto3,oneof" json:"pgo_builds,omitempty"`
	// Distinct image digests whose build facts are held.
	Builds *int64 `protobuf:"varint,4,opt,name=builds,proto3,oneof" json:"builds,omitempty"`
	// Facts arriving from nodes since `since`: how many were received, how many
	// joined to a pod, how many did not, and how many arrived with no image
	// digest to key them by.
	FactsReceived   *int64 `protobuf:"varint,5,opt,name=facts_received,json=factsReceived,proto3,oneof" json:"facts_received,omitempty"`
	FactsJoined     *int64 `protobuf:"varint,6,opt,name=facts_joined,json=factsJoined,proto3,oneof" json:"facts_joined,omitempty"`
	FactsUnjoined   *int64 `protobuf:"varint,7,opt,name=facts_unjoined,json=factsUnjoined,proto3,oneof" json:"facts_unjoined,omitempty"`
	FactsUndigested *int64 `protobuf:"varint,8,opt,name=facts_undigested,json=factsUndigested,proto3,oneof" json:"facts_undigested,omitempty"`
	// Distinct nodes that have delivered an inventory report.
	//
	// Not interchangeable with ScanCoverage.nodes or ProfileCoverage.nodes: the
	// three count participation in three different subsystems, and a node can be
	// in one and not the others.
	NodesReported *int64 `protobuf:"varint,9,opt,name=nodes_reported,json=nodesReported,proto3,oneof" json:"nodes_reported,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryCounters) Reset() {
	*x = InventoryCounters{}
	mi := &file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryCounters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryCounters) ProtoMessage() {}

func (x *InventoryCounters) ProtoReflect() protoreflect.Message {
	mi := &file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryCounters.ProtoReflect.Descriptor instead.
func (*InventoryCounters) Descriptor() ([]byte, []int) {
	return file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_rawDescGZIP(), []int{7}
}

func (x *InventoryCounters) GetRecords() int64 {
	if x != nil && x.Records != nil {
		return *x.Records
	}
	return 0
}

func (x *InventoryCounters) GetGoVersions() int64 {
	if x != nil && x.GoVersions != nil {
		return *x.GoVersions
	}
	return 0
}

func (x *InventoryCounters) GetPgoBuilds() int64 {
	if x != nil && x.PgoBuilds != nil {
		return *x.PgoBuilds
	}
	return 0
}

func (x *InventoryCounters) GetBuilds() int64 {
	if x != nil && x.Builds != nil {
		return *x.Builds
	}
	return 0
}

func (x *InventoryCounters) GetFactsReceived() int64 {
	if x != nil && x.FactsReceived != nil {
		return *x.FactsReceived
	}
	return 0
}

func (x *InventoryCounters) GetFactsJoined() int64 {
	if x != nil && x.FactsJoined != nil {
		return *x.FactsJoined
	}
	return 0
}

func (x *InventoryCounters) GetFactsUnjoined() int64 {
	if x != nil && x.FactsUnjoined != nil {
		return *x.FactsUnjoined
	}
	return 0
}

func (x *InventoryCounters) GetFactsUndigested() int64 {
	if x != nil && x.FactsUndigested != nil {
		return *x.FactsUndigested
	}
	return 0
}

func (x *InventoryCounters) GetNodesReported() int64 {
	if x != nil && x.NodesReported != nil {
		return *x.NodesReported
	}
	return 0
}

// What the on-node process scans did, summed over the nodes that reported.
//
// Absent means the counter was not stated; zero is a number that was counted.
type ScanCoverage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How many nodes contributed the counters in this message.
	//
	// Not interchangeable with InventoryCounters.nodes_reported or
	// ProfileCoverage.nodes: the three count participation in three different
	// subsystems, and a node can be in one and not the others.
	Nodes *int64 `protobuf:"varint,1,opt,name=nodes,proto3,oneof" json:"nodes,omitempty"`
	// The earliest of those nodes' latest reports: the sums below are as current
	// as their stalest contributor, and a node that stopped reporting keeps
	// contributing its last pass. Absent when no node has reported.
	OldestAssertedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=oldest_asserted_at,json=oldestAssertedAt,proto3" json:"oldest_asserted_at,omitempty"`
	// Every process the scans attempted, and the ones found to be Go binaries.
	ProcessesScanned *int64 `protobuf:"varint,3,opt,name=processes_scanned,json=processesScanned,proto3,oneof" json:"processes_scanned,omitempty"`
	GoFound          *int64 `protobuf:"varint,4,opt,name=go_found,json=goFound,proto3,oneof" json:"go_found,omitempty"`
	// What the scans did not report, by reason: the process's pod is outside the
	// collected scope, the process is cluster infrastructure or the agent itself,
	// or its executable carried no Go build information. Together with go_found
	// these account for processes_scanned.
	FilteredScope *int64 `protobuf:"varint,5,opt,name=filtered_scope,json=filteredScope,proto3,oneof" json:"filtered_scope,omitempty"`
	FilteredInfra *int64 `protobuf:"varint,6,opt,name=filtered_infra,json=filteredInfra,proto3,oneof" json:"filtered_infra,omitempty"`
	Unreadable    *int64 `protobuf:"varint,7,opt,name=unreadable,proto3,oneof" json:"unreadable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanCoverage) Reset() {
	*x = ScanCoverage{}
	mi := &file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanCoverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanCoverage) ProtoMessage() {}

func (x *ScanCoverage) ProtoReflect() protoreflect.Message {
	mi := &file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanCoverage.ProtoReflect.Descriptor instead.
func (*ScanCoverage) Descriptor() ([]byte, []int) {
	return file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_rawDescGZIP(), []int{8}
}

func (x *ScanCoverage) GetNodes() int64 {
	if x != nil && x.Nodes != nil {
		return *x.Nodes
	}
	return 0
}

func (x *ScanCoverage) GetOldestAssertedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OldestAssertedAt
	}
	return nil
}

func (x *ScanCoverage) GetProcessesScanned() int64 {
	if x != nil && x.ProcessesScanned != nil {
		return *x.ProcessesScanned
	}
	return 0
}

func (x *ScanCoverage) GetGoFound() int64 {
	if x != nil && x.GoFound != nil {
		return *x.GoFound
	}
	return 0
}

func (x *ScanCoverage) GetFilteredScope() int64 {
	if x != nil && x.FilteredScope != nil {
		return *x.FilteredScope
	}
	return 0
}

func (x *ScanCoverage) GetFilteredInfra() int64 {
	if x != nil && x.FilteredInfra != nil {
		return *x.FilteredInfra
	}
	return 0
}

func (x *ScanCoverage) GetUnreadable() int64 {
	if x != nil && x.Unreadable != nil {
		return *x.Unreadable
	}
	return 0
}

// What the on-node profilers did, summed over the nodes that reported, plus the
// two counts only the receiving side can make. Cumulative since each node
// started, so a node restarting resets its contribution.
//
// Absent means the counter was not stated; zero is a number that was counted.
type ProfileCoverage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How many nodes reported profiling coverage at all.
	//
	// Not interchangeable with InventoryCounters.nodes_reported or
	// ScanCoverage.nodes: the three count participation in three different
	// subsystems, and a node can be in one and not the others.
	Nodes *int64 `protobuf:"varint,1,opt,name=nodes,proto3,oneof" json:"nodes,omitempty"`
	// How many of those nodes are in each profiler state, e.g. "supported",
	// "disabled", or the reason a node's profiler did not start. One node is in
	// exactly one state. Empty when no node reported a state.
	States map[string]int64 `protobuf:"bytes,2,rep,name=states,proto3" json:"states,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Every capture window the profilers cut.
	Windows *int64 `protobuf:"varint,3,opt,name=windows,proto3,oneof" json:"windows,omitempty"`
	// The windows that produced nothing, by reason: no collected scope to profile
	// against, no target from that scope running on the node, or no sample
	// captured in the window at all.
	WindowsNoScope   *int64 `protobuf:"varint,4,opt,name=windows_no_scope,json=windowsNoScope,proto3,oneof" json:"windows_no_scope,omitempty"`
	WindowsNoTargets *int64 `protobuf:"varint,5,opt,name=windows_no_targets,json=windowsNoTargets,proto3,oneof" json:"windows_no_targets,omitempty"`
	WindowsNoSamples *int64 `protobuf:"varint,6,opt,name=windows_no_samples,json=windowsNoSamples,proto3,oneof" json:"windows_no_samples,omitempty"`
	// Profiles the nodes built and what became of them: delivered, refused as
	// holding nothing but runtime and redacted frames, or lost to a delivery that
	// failed.
	ProfilesShipped   *int64 `protobuf:"varint,7,opt,name=profiles_shipped,json=profilesShipped,proto3,oneof" json:"profiles_shipped,omitempty"`
	ProfilesInvalid   *int64 `protobuf:"varint,8,opt,name=profiles_invalid,json=profilesInvalid,proto3,oneof" json:"profiles_invalid,omitempty"`
	ProfilesUnshipped *int64 `protobuf:"varint,9,opt,name=profiles_unshipped,json=profilesUnshipped,proto3,oneof" json:"profiles_unshipped,omitempty"`
	// Samples discarded because the process they came from is outside the
	// collected scope.
	SamplesOutOfScope *int64 `protobuf:"varint,10,opt,name=samples_out_of_scope,json=samplesOutOfScope,proto3,oneof" json:"samples_out_of_scope,omitempty"`
	// What the symbol filter replaced on the nodes: frames of code outside the
	// allow-list, frames that could not be symbolized, and samples that lost at
	// least one frame. Counts only — nothing replaced is named.
	ThirdPartyDropped   *uint64 `protobuf:"varint,11,opt,name=third_party_dropped,json=thirdPartyDropped,proto3,oneof" json:"third_party_dropped,omitempty"`
	UnsymbolizedDropped *uint64 `protobuf:"varint,12,opt,name=unsymbolized_dropped,json=unsymbolizedDropped,proto3,oneof" json:"unsymbolized_dropped,omitempty"`
	SamplesFiltered     *uint64 `protobuf:"varint,13,opt,name=samples_filtered,json=samplesFiltered,proto3,oneof" json:"samples_filtered,omitempty"`
	// Profiles that arrived from nodes, and those dropped because the pod they
	// belong to could not be found. Counted after a node did the work of
	// capturing them, which is why they are not among the node-side counts above.
	ProfilesReceived *uint64 `protobuf:"varint,14,opt,name=profiles_received,json=profilesReceived,proto3,oneof" json:"profiles_received,omitempty"`
	ProfilesUnjoined *uint64 `protobuf:"varint,15,opt,name=profiles_unjoined,json=profilesUnjoined,proto3,oneof" json:"profiles_unjoined,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProfileCoverage) Reset() {
	*x = ProfileCoverage{}
	mi := &file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileCoverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileCoverage) ProtoMessage() {}

func (x *ProfileCoverage) ProtoReflect() protoreflect.Message {
	mi := &file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileCoverage.ProtoReflect.Descriptor instead.
func (*ProfileCoverage) Descriptor() ([]byte, []int) {
	return file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_rawDescGZIP(), []int{9}
}

func (x *ProfileCoverage) GetNodes() int64 {
	if x != nil && x.Nodes != nil {
		return *x.Nodes
	}
	return 0
}

func (x *ProfileCoverage) GetStates() map[string]int64 {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *ProfileCoverage) GetWindows() int64 {
	if x != nil && x.Windows != nil {
		return *x.Windows
	}
	return 0
}

func (x *ProfileCoverage) GetWindowsNoScope() int64 {
	if x != nil && x.WindowsNoScope != nil {
		return *x.WindowsNoScope
	}
	return 0
}

func (x *ProfileCoverage) GetWindowsNoTargets() int64 {
	if x != nil && x.WindowsNoTargets != nil {
		return *x.WindowsNoTargets
	}
	return 0
}

func (x *ProfileCoverage) GetWindowsNoSamples() int64 {
	if x != nil && x.WindowsNoSamples != nil {
		return *x.WindowsNoSamples
	}
	return 0
}

func (x *ProfileCoverage) GetProfilesShipped() int64 {
	if x != nil && x.ProfilesShipped != nil {
		return *x.ProfilesShipped
	}
	return 0
}

func (x *ProfileCoverage) GetProfilesInvalid() int64 {
	if x != nil && x.ProfilesInvalid != nil {
		return *x.ProfilesInvalid
	}
	return 0
}

func (x *ProfileCoverage) GetProfilesUnshipped() int64 {
	if x != nil && x.ProfilesUnshipped != nil {
		return *x.ProfilesUnshipped
	}
	return 0
}

func (x *ProfileCoverage) GetSamplesOutOfScope() int64 {
	if x != nil && x.SamplesOutOfScope != nil {
		return *x.SamplesOutOfScope
	}
	return 0
}

func (x *ProfileCoverage) GetThirdPartyDropped() uint64 {
	if x != nil && x.ThirdPartyDropped != nil {
		return *x.ThirdPartyDropped
	}
	return 0
}

func (x *ProfileCoverage) GetUnsymbolizedDropped() uint64 {
	if x != nil && x.UnsymbolizedDropped != nil {
		return *x.UnsymbolizedDropped
	}
	return 0
}

func (x *ProfileCoverage) GetSamplesFiltered() uint64 {
	if x != nil && x.SamplesFiltered != nil {
		return *x.SamplesFiltered
	}
	return 0
}

func (x *ProfileCoverage) GetProfilesReceived() uint64 {
	if x != nil && x.ProfilesReceived != nil {
		return *x.ProfilesReceived
	}
	return 0
}

func (x *ProfileCoverage) GetProfilesUnjoined() uint64 {
	if x != nil && x.ProfilesUnjoined != nil {
		return *x.ProfilesUnjoined
	}
	return 0
}

// Workload targets by the latest answer to whether they serve a profiling
// endpoint. These are gauges: a number falls when a target leaves the set.
//
// Absent means the counter was not stated; zero is a number that was counted.
type PprofCoverage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Targets whose endpoint was confirmed to exist.
	Confirmed *int64 `protobuf:"varint,1,opt,name=confirmed,proto3,oneof" json:"confirmed,omitempty"`
	// Targets that answered, and have no such endpoint.
	Absent *int64 `protobuf:"varint,2,opt,name=absent,proto3,oneof" json:"absent,omitempty"`
	// Targets that could not be reached to be asked.
	Unreachable *int64 `protobuf:"varint,3,opt,name=unreachable,proto3,oneof" json:"unreachable,omitempty"`
	// Targets the profiling opt-out removed before they were asked. No attempt
	// was made for these, and the number falls when the opt-out is removed.
	ExcludedByAnnotation *int64 `protobuf:"varint,4,opt,name=excluded_by_annotation,json=excludedByAnnotation,proto3,oneof" json:"excluded_by_annotation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PprofCoverage) Reset() {
	*x = PprofCoverage{}
	mi := &file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PprofCoverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PprofCoverage) ProtoMessage() {}

func (x *PprofCoverage) ProtoReflect() protoreflect.Message {
	mi := &file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PprofCoverage.ProtoReflect.Descriptor instead.
func (*PprofCoverage) Descriptor() ([]byte, []int) {
	return file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_rawDescGZIP(), []int{10}
}

func (x *PprofCoverage) GetConfirmed() int64 {
	if x != nil && x.Confirmed != nil {
		return *x.Confirmed
	}
	return 0
}

func (x *PprofCoverage) GetAbsent() int64 {
	if x != nil && x.Absent != nil {
		return *x.Absent
	}
	return 0
}

func (x *PprofCoverage) GetUnreachable() int64 {
	if x != nil && x.Unreachable != nil {
		return *x.Unreachable
	}
	return 0
}

func (x *PprofCoverage) GetExcludedByAnnotation() int64 {
	if x != nil && x.ExcludedByAnnotation != nil {
		return *x.ExcludedByAnnotation
	}
	return 0
}

// What the agent's receiver for on-node reports refused, by reason, cumulative
// since `since`. It is why a node has gone quiet, where the age of that node's
// last contribution says only that it has.
//
// Aggregate only: no refused caller is identified, and no number here names a
// node. Absent means the counter was not stated; zero is a claim that nothing
// was refused for that reason.
type IntakeRejections struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reports whose caller did not authenticate as the node it spoke for.
	Unauthorized *uint64 `protobuf:"varint,1,opt,name=unauthorized,proto3,oneof" json:"unauthorized,omitempty"`
	// Reports over the receiver's size bound. Re-sending one does not help.
	TooLarge *uint64 `protobuf:"varint,2,opt,name=too_large,json=tooLarge,proto3,oneof" json:"too_large,omitempty"`
	// Reports the receiver could not decode, including one carrying a field this
	// build does not know.
	Malformed     *uint64 `protobuf:"varint,3,opt,name=malformed,proto3,oneof" json:"malformed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntakeRejections) Reset() {
	*x = IntakeRejections{}
	mi := &file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntakeRejections) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntakeRejections) ProtoMessage() {}

func (x *IntakeRejections) ProtoReflect() protoreflect.Message {
	mi := &file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntakeRejections.ProtoReflect.Descriptor instead.
func (*IntakeRejections) Descriptor() ([]byte, []int) {
	return file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_rawDescGZIP(), []int{11}
}

func (x *IntakeRejections) GetUnauthorized() uint64 {
	if x != nil && x.Unauthorized != nil {
		return *x.Unauthorized
	}
	return 0
}

func (x *IntakeRejections) GetTooLarge() uint64 {
	if x != nil && x.TooLarge != nil {
		return *x.TooLarge
	}
	return 0
}

func (x *IntakeRejections) GetMalformed() uint64 {
	if x != nil && x.Malformed != nil {
		return *x.Malformed
	}
	return 0
}

// What fetching profiles from confirmed endpoints did, cumulative since
// `since`.
//
// Absent means the counter was not stated; zero is a number that was counted.
type PprofPullCoverage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filtered profiles handed to the sink.
	Shipped *int64 `protobuf:"varint,1,opt,name=shipped,proto3,oneof" json:"shipped,omitempty"`
	// Attempts the target's own runtime would not start a profiler for, which is
	// what a process already running one of its own does. Not a failure of the
	// agent.
	Refused *int64 `protobuf:"varint,2,opt,name=refused,proto3,oneof" json:"refused,omitempty"`
	// Targets whose connection failed.
	Unreachable *int64 `protobuf:"varint,3,opt,name=unreachable,proto3,oneof" json:"unreachable,omitempty"`
	// Profiles that arrived and were not shippable: unparseable, or with nothing
	// left once the symbol allow-list had been applied.
	Invalid       *int64 `protobuf:"varint,4,opt,name=invalid,proto3,oneof" json:"invalid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PprofPullCoverage) Reset() {
	*x = PprofPullCoverage{}
	mi := &file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PprofPullCoverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PprofPullCoverage) ProtoMessage() {}

func (x *PprofPullCoverage) ProtoReflect() protoreflect.Message {
	mi := &file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PprofPullCoverage.ProtoReflect.Descriptor instead.
func (*PprofPullCoverage) Descriptor() ([]byte, []int) {
	return file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_rawDescGZIP(), []int{12}
}

func (x *PprofPullCoverage) GetShipped() int64 {
	if x != nil && x.Shipped != nil {
		return *x.Shipped
	}
	return 0
}

func (x *PprofPullCoverage) GetRefused() int64 {
	if x != nil && x.Refused != nil {
		return *x.Refused
	}
	return 0
}

func (x *PprofPullCoverage) GetUnreachable() int64 {
	if x != nil && x.Unreachable != nil {
		return *x.Unreachable
	}
	return 0
}

func (x *PprofPullCoverage) GetInvalid() int64 {
	if x != nil && x.Invalid != nil {
		return *x.Invalid
	}
	return 0
}

var File_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto protoreflect.FileDescriptor

const file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_rawDesc = "" +
	"\n" +
	";rebuildstack/ingest/kubernetes/v1/collection_coverage.proto\x12!rebuildstack.ingest.kubernetes.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfe\a\n" +
	"\x12CollectionCoverage\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12;\n" +
	"\vcaptured_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"capturedAt\x120\n" +
	"\x05since\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12B\n" +
	"\x05agent\x18\x05 \x01(\v2,.rebuildstack.ingest.kubernetes.v1.AgentInfoR\x05agent\x12I\n" +
	"\asources\x18\x06 \x03(\v2/.rebuildstack.ingest.kubernetes.v1.SourceHealthR\asources\x12I\n" +
	"\x06filter\x18\a \x01(\v21.rebuildstack.ingest.kubernetes.v1.FilterCoverageR\x06filter\x12O\n" +
	"\tplacement\x18\b \x01(\v21.rebuildstack.ingest.kubernetes.v1.PlacementDropsR\tplacement\x12B\n" +
	"\x05nodes\x18\t \x01(\v2,.rebuildstack.ingest.kubernetes.v1.NodeDropsR\x05nodes\x12R\n" +
	"\tinventory\x18\n" +
	" \x01(\v24.rebuildstack.ingest.kubernetes.v1.InventoryCountersR\tinventory\x12C\n" +
	"\x04scan\x18\v \x01(\v2/.rebuildstack.ingest.kubernetes.v1.ScanCoverageR\x04scan\x12F\n" +
	"\x04ebpf\x18\f \x01(\v22.rebuildstack.ingest.kubernetes.v1.ProfileCoverageR\x04ebpf\x12F\n" +
	"\x05pprof\x18\r \x01(\v20.rebuildstack.ingest.kubernetes.v1.PprofCoverageR\x05pprof\x12`\n" +
	"\x11intake_rejections\x18\x0e \x01(\v23.rebuildstack.ingest.kubernetes.v1.IntakeRejectionsR\x10intakeRejections\x12S\n" +
	"\n" +
	"pprof_pull\x18\x0f \x01(\v24.rebuildstack.ingest.kubernetes.v1.PprofPullCoverageR\tpprofPull\"\x92\x01\n" +
	"\tAgentInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12F\n" +
	"\x06config\x18\x02 \x01(\v2..rebuildstack.ingest.kubernetes.v1.ConfigShapeR\x06config\x12#\n" +
	"\rusage_signals\x18\x03 \x03(\tR\fusageSignals\"\xba\x05\n" +
	"\vConfigShape\x120\n" +
	"\x05since\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x122\n" +
	"\x12namespaces_allowed\x18\x02 \x01(\x03H\x00R\x11namespacesAllowed\x88\x01\x01\x120\n" +
	"\x11namespaces_denied\x18\x03 \x01(\x03H\x01R\x10namespacesDenied\x88\x01\x01\x120\n" +
	"\x11profiling_enabled\x18\x04 \x01(\bH\x02R\x10profilingEnabled\x88\x01\x01\x12&\n" +
	"\x0fprofiling_top_n\x18\x05 \x01(\x03R\rprofilingTopN\x12;\n" +
	"\x17pprof_discovery_enabled\x18\x06 \x01(\bH\x03R\x15pprofDiscoveryEnabled\x88\x01\x01\x121\n" +
	"\x12pprof_pull_enabled\x18\a \x01(\bH\x04R\x10pprofPullEnabled\x88\x01\x01\x12;\n" +
	"\x17symbol_prefixes_allowed\x18\b \x01(\x03H\x05R\x15symbolPrefixesAllowed\x88\x01\x01\x123\n" +
	"\x13node_intake_enabled\x18\t \x01(\bH\x06R\x11nodeIntakeEnabled\x88\x01\x01\x12-\n" +
	"\x13spool_max_age_hours\x18\n" +
	" \x01(\x03R\x10spoolMaxAgeHoursB\x15\n" +
	"\x13_namespaces_allowedB\x14\n" +
	"\x12_namespaces_deniedB\x14\n" +
	"\x12_profiling_enabledB\x1a\n" +
	"\x18_pprof_discovery_enabledB\x15\n" +
	"\x13_pprof_pull_enabledB\x1a\n" +
	"\x18_symbol_prefixes_allowedB\x16\n" +
	"\x14_node_intake_enabled\"u\n" +
	"\fSourceHealth\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\x06synced\x18\x02 \x01(\bH\x00R\x06synced\x88\x01\x01\x12\x1d\n" +
	"\afailing\x18\x03 \x01(\bH\x01R\afailing\x88\x01\x01B\t\n" +
	"\a_syncedB\n" +
	"\n" +
	"\b_failing\"\xd6\t\n" +
	"\x0eFilterCoverage\x12(\n" +
	"\rpods_observed\x18\x01 \x01(\x03H\x00R\fpodsObserved\x88\x01\x01\x12?\n" +
	"\x19excluded_namespace_filter\x18\x02 \x01(\x03H\x01R\x17excludedNamespaceFilter\x88\x01\x01\x12G\n" +
	"\x1dexcluded_namespace_annotation\x18\x03 \x01(\x03H\x02R\x1bexcludedNamespaceAnnotation\x88\x01\x01\x12E\n" +
	"\x1cexcluded_workload_annotation\x18\x04 \x01(\x03H\x03R\x1aexcludedWorkloadAnnotation\x88\x01\x01\x12;\n" +
	"\x17excluded_pod_annotation\x18\x05 \x01(\x03H\x04R\x15excludedPodAnnotation\x88\x01\x01\x12G\n" +
	"\x1dexcluded_profiling_annotation\x18\x06 \x01(\x03H\x05R\x1bexcludedProfilingAnnotation\x88\x01\x01\x127\n" +
	"\x15workload_unknown_kind\x18\a \x01(\x03H\x06R\x13workloadUnknownKind\x88\x01\x01\x123\n" +
	"\x13workload_not_cached\x18\b \x01(\x03H\aR\x11workloadNotCached\x88\x01\x01\x12(\n" +
	"\rjobs_observed\x18\t \x01(\x03H\bR\fjobsObserved\x88\x01\x01\x12H\n" +
	"\x1ejobs_excluded_namespace_filter\x18\n" +
	" \x01(\x03H\tR\x1bjobsExcludedNamespaceFilter\x88\x01\x01\x12P\n" +
	"\"jobs_excluded_namespace_annotation\x18\v \x01(\x03H\n" +
	"R\x1fjobsExcludedNamespaceAnnotation\x88\x01\x01\x12N\n" +
	"!jobs_excluded_workload_annotation\x18\f \x01(\x03H\vR\x1ejobsExcludedWorkloadAnnotation\x88\x01\x01\x12=\n" +
	"\x18jobs_excluded_annotation\x18\r \x01(\x03H\fR\x16jobsExcludedAnnotation\x88\x01\x01B\x10\n" +
	"\x0e_pods_observedB\x1c\n" +
	"\x1a_excluded_namespace_filterB \n" +
	"\x1e_excluded_namespace_annotationB\x1f\n" +
	"\x1d_excluded_workload_annotationB\x1a\n" +
	"\x18_excluded_pod_annotationB \n" +
	"\x1e_excluded_profiling_annotationB\x18\n" +
	"\x16_workload_unknown_kindB\x16\n" +
	"\x14_workload_not_cachedB\x10\n" +
	"\x0e_jobs_observedB!\n" +
	"\x1f_jobs_excluded_namespace_filterB%\n" +
	"#_jobs_excluded_namespace_annotationB$\n" +
	"\"_jobs_excluded_workload_annotationB\x1b\n" +
	"\x19_jobs_excluded_annotation\"\x8b\x01\n" +
	"\x0ePlacementDrops\x12*\n" +
	"\x0evalues_dropped\x18\x01 \x01(\x03H\x00R\rvaluesDropped\x88\x01\x01\x12(\n" +
	"\rterms_dropped\x18\x02 \x01(\x03H\x01R\ftermsDropped\x88\x01\x01B\x11\n" +
	"\x0f_values_droppedB\x10\n" +
	"\x0e_terms_dropped\"\x96\x02\n" +
	"\tNodeDrops\x122\n" +
	"\x12conditions_dropped\x18\x01 \x01(\x03H\x00R\x11conditionsDropped\x88\x01\x01\x12,\n" +
	"\x0fdevices_dropped\x18\x02 \x01(\x03H\x01R\x0edevicesDropped\x88\x01\x01\x12*\n" +
	"\x0etaints_dropped\x18\x03 \x01(\x03H\x02R\rtaintsDropped\x88\x01\x01\x12*\n" +
	"\x0evalues_dropped\x18\x04 \x01(\x03H\x03R\rvaluesDropped\x88\x01\x01B\x15\n" +
	"\x13_conditions_droppedB\x12\n" +
	"\x10_devices_droppedB\x11\n" +
	"\x0f_taints_droppedB\x11\n" +
	"\x0f_values_dropped\"\x8a\x04\n" +
	"\x11InventoryCounters\x12\x1d\n" +
	"\arecords\x18\x01 \x01(\x03H\x00R\arecords\x88\x01\x01\x12$\n" +
	"\vgo_versions\x18\x02 \x01(\x03H\x01R\n" +
	"goVersions\x88\x01\x01\x12\"\n" +
	"\n" +
	"pgo_builds\x18\x03 \x01(\x03H\x02R\tpgoBuilds\x88\x01\x01\x12\x1b\n" +
	"\x06builds\x18\x04 \x01(\x03H\x03R\x06builds\x88\x01\x01\x12*\n" +
	"\x0efacts_received\x18\x05 \x01(\x03H\x04R\rfactsReceived\x88\x01\x01\x12&\n" +
	"\ffacts_joined\x18\x06 \x01(\x03H\x05R\vfactsJoined\x88\x01\x01\x12*\n" +
	"\x0efacts_unjoined\x18\a \x01(\x03H\x06R\rfactsUnjoined\x88\x01\x01\x12.\n" +
	"\x10facts_undigested\x18\b \x01(\x03H\aR\x0ffactsUndigested\x88\x01\x01\x12*\n" +
	"\x0enodes_reported\x18\t \x01(\x03H\bR\rnodesReported\x88\x01\x01B\n" +
	"\n" +
	"\b_recordsB\x0e\n" +
	"\f_go_versionsB\r\n" +
	"\v_pgo_buildsB\t\n" +
	"\a_buildsB\x11\n" +
	"\x0f_facts_receivedB\x0f\n" +
	"\r_facts_joinedB\x11\n" +
	"\x0f_facts_unjoinedB\x13\n" +
	"\x11_facts_undigestedB\x11\n" +
	"\x0f_nodes_reported\"\xa4\x03\n" +
	"\fScanCoverage\x12\x19\n" +
	"\x05nodes\x18\x01 \x01(\x03H\x00R\x05nodes\x88\x01\x01\x12H\n" +
	"\x12oldest_asserted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x10oldestAssertedAt\x120\n" +
	"\x11processes_scanned\x18\x03 \x01(\x03H\x01R\x10processesScanned\x88\x01\x01\x12\x1e\n" +
	"\bgo_found\x18\x04 \x01(\x03H\x02R\agoFound\x88\x01\x01\x12*\n" +
	"\x0efiltered_scope\x18\x05 \x01(\x03H\x03R\rfilteredScope\x88\x01\x01\x12*\n" +
	"\x0efiltered_infra\x18\x06 \x01(\x03H\x04R\rfilteredInfra\x88\x01\x01\x12#\n" +
	"\n" +
	"unreadable\x18\a \x01(\x03H\x05R\n" +
	"unreadable\x88\x01\x01B\b\n" +
	"\x06_nodesB\x14\n" +
	"\x12_processes_scannedB\v\n" +
	"\t_go_foundB\x11\n" +
	"\x0f_filtered_scopeB\x11\n" +
	"\x0f_filtered_infraB\r\n" +
	"\v_unreadable\"\xe3\b\n" +
	"\x0fProfileCoverage\x12\x19\n" +
	"\x05nodes\x18\x01 \x01(\x03H\x00R\x05nodes\x88\x01\x01\x12V\n" +
	"\x06states\x18\x02 \x03(\v2>.rebuildstack.ingest.kubernetes.v1.ProfileCoverage.StatesEntryR\x06states\x12\x1d\n" +
	"\awindows\x18\x03 \x01(\x03H\x01R\awindows\x88\x01\x01\x12-\n" +
	"\x10windows_no_scope\x18\x04 \x01(\x03H\x02R\x0ewindowsNoScope\x88\x01\x01\x121\n" +
	"\x12windows_no_targets\x18\x05 \x01(\x03H\x03R\x10windowsNoTargets\x88\x01\x01\x121\n" +
	"\x12windows_no_samples\x18\x06 \x01(\x03H\x04R\x10windowsNoSamples\x88\x01\x01\x12.\n" +
	"\x10profiles_shipped\x18\a \x01(\x03H\x05R\x0fprofilesShipped\x88\x01\x01\x12.\n" +
	"\x10profiles_invalid\x18\b \x01(\x03H\x06R\x0fprofilesInvalid\x88\x01\x01\x122\n" +
	"\x12profiles_unshipped\x18\t \x01(\x03H\aR\x11profilesUnshipped\x88\x01\x01\x124\n" +
	"\x14samples_out_of_scope\x18\n" +
	" \x01(\x03H\bR\x11samplesOutOfScope\x88\x01\x01\x123\n" +
	"\x13third_party_dropped\x18\v \x01(\x04H\tR\x11thirdPartyDropped\x88\x01\x01\x126\n" +
	"\x14unsymbolized_dropped\x18\f \x01(\x04H\n" +
	"R\x13unsymbolizedDropped\x88\x01\x01\x12.\n" +
	"\x10samples_filtered\x18\r \x01(\x04H\vR\x0fsamplesFiltered\x88\x01\x01\x120\n" +
	"\x11profiles_received\x18\x0e \x01(\x04H\fR\x10profilesReceived\x88\x01\x01\x120\n" +
	"\x11profiles_unjoined\x18\x0f \x01(\x04H\rR\x10profilesUnjoined\x88\x01\x01\x1a9\n" +
	"\vStatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01B\b\n" +
	"\x06_nodesB\n" +
	"\n" +
	"\b_windowsB\x13\n" +
	"\x11_windows_no_scopeB\x15\n" +
	"\x13_windows_no_targetsB\x15\n" +
	"\x13_windows_no_samplesB\x13\n" +
	"\x11_profiles_shippedB\x13\n" +
	"\x11_profiles_invalidB\x15\n" +
	"\x13_profiles_unshippedB\x17\n" +
	"\x15_samples_out_of_scopeB\x16\n" +
	"\x14_third_party_droppedB\x17\n" +
	"\x15_unsymbolized_droppedB\x13\n" +
	"\x11_samples_filteredB\x14\n" +
	"\x12_profiles_receivedB\x14\n" +
	"\x12_profiles_unjoined\"\xf5\x01\n" +
	"\rPprofCoverage\x12!\n" +
	"\tconfirmed\x18\x01 \x01(\x03H\x00R\tconfirmed\x88\x01\x01\x12\x1b\n" +
	"\x06absent\x18\x02 \x01(\x03H\x01R\x06absent\x88\x01\x01\x12%\n" +
	"\vunreachable\x18\x03 \x01(\x03H\x02R\vunreachable\x88\x01\x01\x129\n" +
	"\x16excluded_by_annotation\x18\x04 \x01(\x03H\x03R\x14excludedByAnnotation\x88\x01\x01B\f\n" +
	"\n" +
	"_confirmedB\t\n" +
	"\a_absentB\x0e\n" +
	"\f_unreachableB\x19\n" +
	"\x17_excluded_by_annotation\"\xad\x01\n" +
	"\x10IntakeRejections\x12'\n" +
	"\funauthorized\x18\x01 \x01(\x04H\x00R\funauthorized\x88\x01\x01\x12 \n" +
	"\ttoo_large\x18\x02 \x01(\x04H\x01R\btooLarge\x88\x01\x01\x12!\n" +
	"\tmalformed\x18\x03 \x01(\x04H\x02R\tmalformed\x88\x01\x01B\x0f\n" +
	"\r_unauthorizedB\f\n" +
	"\n" +
	"_too_largeB\f\n" +
	"\n" +
	"_malformed\"\xcb\x01\n" +
	"\x11PprofPullCoverage\x12\x1d\n" +
	"\ashipped\x18\x01 \x01(\x03H\x00R\ashipped\x88\x01\x01\x12\x1d\n" +
	"\arefused\x18\x02 \x01(\x03H\x01R\arefused\x88\x01\x01\x12%\n" +
	"\vunreachable\x18\x03 \x01(\x03H\x02R\vunreachable\x88\x01\x01\x12\x1d\n" +
	"\ainvalid\x18\x04 \x01(\x03H\x03R\ainvalid\x88\x01\x01B\n" +
	"\n" +
	"\b_shippedB\n" +
	"\n" +
	"\b_refusedB\x0e\n" +
	"\f_unreachableB\n" +
	"\n" +
	"\b_invalidBOZMgithub.com/RebuildStackCo/runtime-agent/internal/pb/kubernetesv1;kubernetesv1b\x06proto3"

var (
	file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_rawDescOnce sync.Once
	file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_rawDescData []byte
)

func file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_rawDescGZIP() []byte {
	file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_rawDescOnce.Do(func() {
		file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_rawDesc), len(file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_rawDesc)))
	})
	return file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_rawDescData
}

var file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_goTypes = []any{
	(*CollectionCoverage)(nil),    // 0: rebuildstack.ingest.kubernetes.v1.CollectionCoverage
	(*AgentInfo)(nil),             // 1: rebuildstack.ingest.kubernetes.v1.AgentInfo
	(*ConfigShape)(nil),           // 2: rebuildstack.ingest.kubernetes.v1.ConfigShape
	(*SourceHealth)(nil),          // 3: rebuildstack.ingest.kubernetes.v1.SourceHealth
	(*FilterCoverage)(nil),        // 4: rebuildstack.ingest.kubernetes.v1.FilterCoverage
	(*PlacementDrops)(nil),        // 5: rebuildstack.ingest.kubernetes.v1.PlacementDrops
	(*NodeDrops)(nil),             // 6: rebuildstack.ingest.kubernetes.v1.NodeDrops
	(*InventoryCounters)(nil),     // 7: rebuildstack.ingest.kubernetes.v1.InventoryCounters
	(*ScanCoverage)(nil),          // 8: rebuildstack.ingest.kubernetes.v1.ScanCoverage
	(*ProfileCoverage)(nil),       // 9: rebuildstack.ingest.kubernetes.v1.ProfileCoverage
	(*PprofCoverage)(nil),         // 10: rebuildstack.ingest.kubernetes.v1.PprofCoverage
	(*IntakeRejections)(nil),      // 11: rebuildstack.ingest.kubernetes.v1.IntakeRejections
	(*PprofPullCoverage)(nil),     // 12: rebuildstack.ingest.kubernetes.v1.PprofPullCoverage
	nil,                           // 13: rebuildstack.ingest.kubernetes.v1.ProfileCoverage.StatesEntry
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_depIdxs = []int32{
	14, // 0: rebuildstack.ingest.kubernetes.v1.CollectionCoverage.captured_at:type_name -> google.protobuf.Timestamp
	14, // 1: rebuildstack.ingest.kubernetes.v1.CollectionCoverage.since:type_name -> google.protobuf.Timestamp
	1,  // 2: rebuildstack.ingest.kubernetes.v1.CollectionCoverage.agent:type_name -> rebuildstack.ingest.kubernetes.v1.AgentInfo
	3,  // 3: rebuildstack.ingest.kubernetes.v1.CollectionCoverage.sources:type_name -> rebuildstack.ingest.kubernetes.v1.SourceHealth
	4,  // 4: rebuildstack.ingest.kubernetes.v1.CollectionCoverage.filter:type_name -> rebuildstack.ingest.kubernetes.v1.FilterCoverage
	5,  // 5: rebuildstack.ingest.kubernetes.v1.CollectionCoverage.placement:type_name -> rebuildstack.ingest.kubernetes.v1.PlacementDrops
	6,  // 6: rebuildstack.ingest.kubernetes.v1.CollectionCoverage.nodes:type_name -> rebuildstack.ingest.kubernetes.v1.NodeDrops
	7,  // 7: rebuildstack.ingest.kubernetes.v1.CollectionCoverage.inventory:type_name -> rebuildstack.ingest.kubernetes.v1.InventoryCounters
	8,  // 8: rebuildstack.ingest.kubernetes.v1.CollectionCoverage.scan:type_name -> rebuildstack.ingest.kubernetes.v1.ScanCoverage
	9,  // 9: rebuildstack.ingest.kubernetes.v1.CollectionCoverage.ebpf:type_name -> rebuildstack.ingest.kubernetes.v1.ProfileCoverage
	10, // 10: rebuildstack.ingest.kubernetes.v1.CollectionCoverage.pprof:type_name -> rebuildstack.ingest.kubernetes.v1.PprofCoverage
	11, // 11: rebuildstack.ingest.kubernetes.v1.CollectionCoverage.intake_rejections:type_name -> rebuildstack.ingest.kubernetes.v1.IntakeRejections
	12, // 12: rebuildstack.ingest.kubernetes.v1.CollectionCoverage.pprof_pull:type_name -> rebuildstack.ingest.kubernetes.v1.PprofPullCoverage
	2,  // 13: rebuildstack.ingest.kubernetes.v1.AgentInfo.config:type_name -> rebuildstack.ingest.kubernetes.v1.ConfigShape
	14, // 14: rebuildstack.ingest.kubernetes.v1.ConfigShape.since:type_name -> google.protobuf.Timestamp
	14, // 15: rebuildstack.ingest.kubernetes.v1.ScanCoverage.oldest_asserted_at:type_name -> google.protobuf.Timestamp
	13, // 16: rebuildstack.ingest.kubernetes.v1.ProfileCoverage.states:type_name -> rebuildstack.ingest.kubernetes.v1.ProfileCoverage.StatesEntry
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_init() }
func file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_init() {
	if File_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto != nil {
		return
	}
	file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[2].OneofWrappers = []any{}
	file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[3].OneofWrappers = []any{}
	file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[4].OneofWrappers = []any{}
	file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[5].OneofWrappers = []any{}
	file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[6].OneofWrappers = []any{}
	file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[7].OneofWrappers = []any{}
	file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[8].OneofWrappers = []any{}
	file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[9].OneofWrappers = []any{}
	file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[10].OneofWrappers = []any{}
	file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[11].OneofWrappers = []any{}
	file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_rawDesc), len(file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_goTypes,
		DependencyIndexes: file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_depIdxs,
		MessageInfos:      file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_msgTypes,
	}.Build()
	File_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto = out.File
	file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_goTypes = nil
	file_rebuildstack_ingest_kubernetes_v1_collection_coverage_proto_depIdxs = nil
}
