// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: rebuildstack/ingest/kubernetes/v1/node_lifecycle.proto

// The `node_lifecycle` payload: machines arriving in and leaving the cluster.

package kubernetesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The nodes that joined or left the cluster within one window.
//
// The window is a delivery boundary and not an aggregation: every record
// carries its own instant, and nothing here is summed over the window.
type NodeLifecycle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The payload kind: "node_lifecycle".
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// The class of claim these facts are: "journal" — derived from object
	// metadata that records what happened, rather than from current state.
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// The window this payload covers: when it begins, and how many seconds long
	// it is. Together they are the payload's key.
	WindowStart   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=window_start,json=windowStart,proto3" json:"window_start,omitempty"`
	WindowSeconds int64                  `protobuf:"varint,4,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"`
	// One record per node and event within the window. A node that joined and
	// left in the same window has two.
	Records       []*NodeEvent `protobuf:"bytes,5,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeLifecycle) Reset() {
	*x = NodeLifecycle{}
	mi := &file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeLifecycle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeLifecycle) ProtoMessage() {}

func (x *NodeLifecycle) ProtoReflect() protoreflect.Message {
	mi := &file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeLifecycle.ProtoReflect.Descriptor instead.
func (*NodeLifecycle) Descriptor() ([]byte, []int) {
	return file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_rawDescGZIP(), []int{0}
}

func (x *NodeLifecycle) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *NodeLifecycle) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *NodeLifecycle) GetWindowStart() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowStart
	}
	return nil
}

func (x *NodeLifecycle) GetWindowSeconds() int64 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

func (x *NodeLifecycle) GetRecords() []*NodeEvent {
	if x != nil {
		return x.Records
	}
	return nil
}

// One node arriving in or leaving the cluster.
//
// It carries the machine's own size at the instant of the event rather than
// pointing at a node inventory: a node that has left is absent from every later
// NodeMetadata, so this is the only record of how big what left was.
type NodeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The node's name in the cluster.
	Node string `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	// "joined" or "left".
	Event string `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	// When it happened. For a join this is the node object's own creation
	// timestamp; for a departure it is when the agent noticed, because a deleted
	// object carries no deletion time to read. at_observed says which.
	At *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=at,proto3" json:"at,omitempty"`
	// True when `at` is the instant the agent noticed rather than the instant the
	// event carries. Absent means the provenance of `at` was not stated; false is
	// a claim that `at` is the event's own.
	AtObserved *bool `protobuf:"varint,4,opt,name=at_observed,json=atObserved,proto3,oneof" json:"at_observed,omitempty"`
	// What the machine was, at the instant of the event. Each is empty when the
	// node carried no such label.
	InstanceType string `protobuf:"bytes,5,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"`
	CapacityType string `protobuf:"bytes,6,opt,name=capacity_type,json=capacityType,proto3" json:"capacity_type,omitempty"`
	Zone         string `protobuf:"bytes,7,opt,name=zone,proto3" json:"zone,omitempty"`
	// Thousandths of a CPU core: 1000 is one core.
	CapacityCpuMilli *int64 `protobuf:"varint,8,opt,name=capacity_cpu_milli,json=capacityCpuMilli,proto3,oneof" json:"capacity_cpu_milli,omitempty"`
	// Bytes of RAM.
	CapacityMemoryBytes *int64 `protobuf:"varint,9,opt,name=capacity_memory_bytes,json=capacityMemoryBytes,proto3,oneof" json:"capacity_memory_bytes,omitempty"`
	// The extended resources the node advertised. Empty means it advertised none
	// this schema carries; see NodeDevice for what that excludes.
	Devices []*NodeDevice `protobuf:"bytes,10,rep,name=devices,proto3" json:"devices,omitempty"`
	// The window this record is filed in, repeated from the payload carrying it,
	// so a record read on its own still states which window it belongs to.
	WindowStart   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=window_start,json=windowStart,proto3" json:"window_start,omitempty"`
	WindowSeconds int64                  `protobuf:"varint,12,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeEvent) Reset() {
	*x = NodeEvent{}
	mi := &file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeEvent) ProtoMessage() {}

func (x *NodeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeEvent.ProtoReflect.Descriptor instead.
func (*NodeEvent) Descriptor() ([]byte, []int) {
	return file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_rawDescGZIP(), []int{1}
}

func (x *NodeEvent) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *NodeEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *NodeEvent) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *NodeEvent) GetAtObserved() bool {
	if x != nil && x.AtObserved != nil {
		return *x.AtObserved
	}
	return false
}

func (x *NodeEvent) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *NodeEvent) GetCapacityType() string {
	if x != nil {
		return x.CapacityType
	}
	return ""
}

func (x *NodeEvent) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *NodeEvent) GetCapacityCpuMilli() int64 {
	if x != nil && x.CapacityCpuMilli != nil {
		return *x.CapacityCpuMilli
	}
	return 0
}

func (x *NodeEvent) GetCapacityMemoryBytes() int64 {
	if x != nil && x.CapacityMemoryBytes != nil {
		return *x.CapacityMemoryBytes
	}
	return 0
}

func (x *NodeEvent) GetDevices() []*NodeDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *NodeEvent) GetWindowStart() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowStart
	}
	return nil
}

func (x *NodeEvent) GetWindowSeconds() int64 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

var File_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto protoreflect.FileDescriptor

const file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_rawDesc = "" +
	"\n" +
	"6rebuildstack/ingest/kubernetes/v1/node_lifecycle.proto\x12!rebuildstack.ingest.kubernetes.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a3rebuildstack/ingest/kubernetes/v1/node_device.proto\"\xe9\x01\n" +
	"\rNodeLifecycle\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12=\n" +
	"\fwindow_start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vwindowStart\x12%\n" +
	"\x0ewindow_seconds\x18\x04 \x01(\x03R\rwindowSeconds\x12F\n" +
	"\arecords\x18\x05 \x03(\v2,.rebuildstack.ingest.kubernetes.v1.NodeEventR\arecords\"\xc1\x04\n" +
	"\tNodeEvent\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12*\n" +
	"\x02at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12$\n" +
	"\vat_observed\x18\x04 \x01(\bH\x00R\n" +
	"atObserved\x88\x01\x01\x12#\n" +
	"\rinstance_type\x18\x05 \x01(\tR\finstanceType\x12#\n" +
	"\rcapacity_type\x18\x06 \x01(\tR\fcapacityType\x12\x12\n" +
	"\x04zone\x18\a \x01(\tR\x04zone\x121\n" +
	"\x12capacity_cpu_milli\x18\b \x01(\x03H\x01R\x10capacityCpuMilli\x88\x01\x01\x127\n" +
	"\x15capacity_memory_bytes\x18\t \x01(\x03H\x02R\x13capacityMemoryBytes\x88\x01\x01\x12G\n" +
	"\adevices\x18\n" +
	" \x03(\v2-.rebuildstack.ingest.kubernetes.v1.NodeDeviceR\adevices\x12=\n" +
	"\fwindow_start\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vwindowStart\x12%\n" +
	"\x0ewindow_seconds\x18\f \x01(\x03R\rwindowSecondsB\x0e\n" +
	"\f_at_observedB\x15\n" +
	"\x13_capacity_cpu_milliB\x18\n" +
	"\x16_capacity_memory_bytesBOZMgithub.com/RebuildStackCo/runtime-agent/internal/pb/kubernetesv1;kubernetesv1b\x06proto3"

var (
	file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_rawDescOnce sync.Once
	file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_rawDescData []byte
)

func file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_rawDescGZIP() []byte {
	file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_rawDescOnce.Do(func() {
		file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_rawDesc), len(file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_rawDesc)))
	})
	return file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_rawDescData
}

var file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_goTypes = []any{
	(*NodeLifecycle)(nil),         // 0: rebuildstack.ingest.kubernetes.v1.NodeLifecycle
	(*NodeEvent)(nil),             // 1: rebuildstack.ingest.kubernetes.v1.NodeEvent
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*NodeDevice)(nil),            // 3: rebuildstack.ingest.kubernetes.v1.NodeDevice
}
var file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_depIdxs = []int32{
	2, // 0: rebuildstack.ingest.kubernetes.v1.NodeLifecycle.window_start:type_name -> google.protobuf.Timestamp
	1, // 1: rebuildstack.ingest.kubernetes.v1.NodeLifecycle.records:type_name -> rebuildstack.ingest.kubernetes.v1.NodeEvent
	2, // 2: rebuildstack.ingest.kubernetes.v1.NodeEvent.at:type_name -> google.protobuf.Timestamp
	3, // 3: rebuildstack.ingest.kubernetes.v1.NodeEvent.devices:type_name -> rebuildstack.ingest.kubernetes.v1.NodeDevice
	2, // 4: rebuildstack.ingest.kubernetes.v1.NodeEvent.window_start:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_init() }
func file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_init() {
	if File_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto != nil {
		return
	}
	file_rebuildstack_ingest_kubernetes_v1_node_device_proto_init()
	file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_rawDesc), len(file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_goTypes,
		DependencyIndexes: file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_depIdxs,
		MessageInfos:      file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_msgTypes,
	}.Build()
	File_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto = out.File
	file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_goTypes = nil
	file_rebuildstack_ingest_kubernetes_v1_node_lifecycle_proto_depIdxs = nil
}
