// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: rebuildstack/ingest/kubernetes/v1/node_metadata.proto

// The `node_metadata` payload: the machines the cluster is running on.

package kubernetesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The nodes the cluster holds, with what each machine is and what it can carry.
//
// A superseding snapshot keyed by the payload kind: the newest one replaces its
// predecessor entirely, and a node absent from it is a node that is no longer
// in the cluster. What left is recorded in NodeLifecycle instead.
type NodeMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The payload kind: "node_metadata".
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// The class of claim these facts are: "structural" — read from an object's
	// spec or status, rather than measured from an instrument or sampled.
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// When the snapshot was taken. It dates the assembly, not each fact in it.
	CapturedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"`
	// Every node in the cluster at that instant.
	Nodes         []*NodeInfo `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMetadata) Reset() {
	*x = NodeMetadata{}
	mi := &file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetadata) ProtoMessage() {}

func (x *NodeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetadata.ProtoReflect.Descriptor instead.
func (*NodeMetadata) Descriptor() ([]byte, []int) {
	return file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *NodeMetadata) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *NodeMetadata) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *NodeMetadata) GetCapturedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CapturedAt
	}
	return nil
}

func (x *NodeMetadata) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// One node: what kind of machine it is, where it sits, what software runs it,
// what state it reports and what it refuses to run.
type NodeInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The node's name in the cluster. Other payloads name nodes by this string.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The machine type as the cloud provider labels it, e.g. "m6i.large". Empty
	// when the node carries no such label.
	InstanceType string `protobuf:"bytes,2,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"`
	// How the machine is bought: "spot", "on-demand", or empty when the node's
	// labels do not settle it.
	CapacityType string `protobuf:"bytes,3,opt,name=capacity_type,json=capacityType,proto3" json:"capacity_type,omitempty"`
	// The failure domain the node is in, from its own topology label. Empty when
	// the node carries no such label.
	Zone string `protobuf:"bytes,4,opt,name=zone,proto3" json:"zone,omitempty"`
	// The wider region the zone belongs to, from the node's own topology label.
	// Empty when the node carries no such label.
	Region string `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	// The kernel the node runs, as the kubelet reports it, e.g. "6.1.0-generic".
	KernelVersion string `protobuf:"bytes,6,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	// The node's CPU architecture, e.g. "amd64", "arm64".
	Architecture string `protobuf:"bytes,7,opt,name=architecture,proto3" json:"architecture,omitempty"`
	// The kubelet's own version, e.g. "v1.31.4".
	KubeletVersion string `protobuf:"bytes,8,opt,name=kubelet_version,json=kubeletVersion,proto3" json:"kubelet_version,omitempty"`
	// The node's OS image, e.g. "Ubuntu 22.04.5 LTS", and its operating system,
	// e.g. "linux".
	OsImage         string `protobuf:"bytes,9,opt,name=os_image,json=osImage,proto3" json:"os_image,omitempty"`
	OperatingSystem string `protobuf:"bytes,10,opt,name=operating_system,json=operatingSystem,proto3" json:"operating_system,omitempty"`
	// The container runtime and its version, e.g. "containerd://1.7.22".
	ContainerRuntime string `protobuf:"bytes,11,opt,name=container_runtime,json=containerRuntime,proto3" json:"container_runtime,omitempty"`
	// The node object's own creation timestamp: when the machine joined, not when
	// it was read. Absent when the node object stated none.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Thousandths of a CPU core: 1000 is one core.
	CapacityCpuMilli    *int64 `protobuf:"varint,13,opt,name=capacity_cpu_milli,json=capacityCpuMilli,proto3,oneof" json:"capacity_cpu_milli,omitempty"`
	AllocatableCpuMilli *int64 `protobuf:"varint,14,opt,name=allocatable_cpu_milli,json=allocatableCpuMilli,proto3,oneof" json:"allocatable_cpu_milli,omitempty"`
	// Bytes of RAM.
	CapacityMemoryBytes    *int64 `protobuf:"varint,15,opt,name=capacity_memory_bytes,json=capacityMemoryBytes,proto3,oneof" json:"capacity_memory_bytes,omitempty"`
	AllocatableMemoryBytes *int64 `protobuf:"varint,16,opt,name=allocatable_memory_bytes,json=allocatableMemoryBytes,proto3,oneof" json:"allocatable_memory_bytes,omitempty"`
	// Bytes of node-local disk, which images, logs and emptyDir volumes share.
	CapacityEphemeralStorageBytes    *int64 `protobuf:"varint,17,opt,name=capacity_ephemeral_storage_bytes,json=capacityEphemeralStorageBytes,proto3,oneof" json:"capacity_ephemeral_storage_bytes,omitempty"`
	AllocatableEphemeralStorageBytes *int64 `protobuf:"varint,18,opt,name=allocatable_ephemeral_storage_bytes,json=allocatableEphemeralStorageBytes,proto3,oneof" json:"allocatable_ephemeral_storage_bytes,omitempty"`
	// How many pods the kubelet will run here. A node idle in CPU and memory can
	// still be full at this bound.
	CapacityPods    *int64 `protobuf:"varint,19,opt,name=capacity_pods,json=capacityPods,proto3,oneof" json:"capacity_pods,omitempty"`
	AllocatablePods *int64 `protobuf:"varint,20,opt,name=allocatable_pods,json=allocatablePods,proto3,oneof" json:"allocatable_pods,omitempty"`
	// The extended resources the node advertises. Empty means it advertises none
	// this schema carries; see NodeDevice for what that excludes.
	Devices []*NodeDevice `protobuf:"bytes,21,rep,name=devices,proto3" json:"devices,omitempty"`
	// The node's conditions, of the five types this schema carries: Ready,
	// MemoryPressure, DiskPressure, PIDPressure, NetworkUnavailable. All five are
	// carried whenever the node reports them, healthy or not, and conditions of
	// other types are counted in CollectionCoverage.nodes.conditions_dropped.
	//
	// Empty is not a healthy node. It is a node that reported no condition at all.
	Conditions []*NodeCondition `protobuf:"bytes,22,rep,name=conditions,proto3" json:"conditions,omitempty"`
	// What the node refuses to run, unless a pod tolerates it. Empty means it
	// refuses nothing; taints whose strings were too long to carry are counted in
	// CollectionCoverage.nodes.taints_dropped.
	Taints        []*NodeTaint `protobuf:"bytes,23,rep,name=taints,proto3" json:"taints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *NodeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeInfo) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *NodeInfo) GetCapacityType() string {
	if x != nil {
		return x.CapacityType
	}
	return ""
}

func (x *NodeInfo) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *NodeInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *NodeInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *NodeInfo) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *NodeInfo) GetKubeletVersion() string {
	if x != nil {
		return x.KubeletVersion
	}
	return ""
}

func (x *NodeInfo) GetOsImage() string {
	if x != nil {
		return x.OsImage
	}
	return ""
}

func (x *NodeInfo) GetOperatingSystem() string {
	if x != nil {
		return x.OperatingSystem
	}
	return ""
}

func (x *NodeInfo) GetContainerRuntime() string {
	if x != nil {
		return x.ContainerRuntime
	}
	return ""
}

func (x *NodeInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NodeInfo) GetCapacityCpuMilli() int64 {
	if x != nil && x.CapacityCpuMilli != nil {
		return *x.CapacityCpuMilli
	}
	return 0
}

func (x *NodeInfo) GetAllocatableCpuMilli() int64 {
	if x != nil && x.AllocatableCpuMilli != nil {
		return *x.AllocatableCpuMilli
	}
	return 0
}

func (x *NodeInfo) GetCapacityMemoryBytes() int64 {
	if x != nil && x.CapacityMemoryBytes != nil {
		return *x.CapacityMemoryBytes
	}
	return 0
}

func (x *NodeInfo) GetAllocatableMemoryBytes() int64 {
	if x != nil && x.AllocatableMemoryBytes != nil {
		return *x.AllocatableMemoryBytes
	}
	return 0
}

func (x *NodeInfo) GetCapacityEphemeralStorageBytes() int64 {
	if x != nil && x.CapacityEphemeralStorageBytes != nil {
		return *x.CapacityEphemeralStorageBytes
	}
	return 0
}

func (x *NodeInfo) GetAllocatableEphemeralStorageBytes() int64 {
	if x != nil && x.AllocatableEphemeralStorageBytes != nil {
		return *x.AllocatableEphemeralStorageBytes
	}
	return 0
}

func (x *NodeInfo) GetCapacityPods() int64 {
	if x != nil && x.CapacityPods != nil {
		return *x.CapacityPods
	}
	return 0
}

func (x *NodeInfo) GetAllocatablePods() int64 {
	if x != nil && x.AllocatablePods != nil {
		return *x.AllocatablePods
	}
	return 0
}

func (x *NodeInfo) GetDevices() []*NodeDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *NodeInfo) GetConditions() []*NodeCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *NodeInfo) GetTaints() []*NodeTaint {
	if x != nil {
		return x.Taints
	}
	return nil
}

// One condition the node reports about itself. The free-text `message` the
// kubelet writes beside it is not carried.
type NodeCondition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One of Ready, MemoryPressure, DiskPressure, PIDPressure,
	// NetworkUnavailable.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// "True", "False" or "Unknown", as the node reports it.
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// The node's own machine-readable reason token, e.g. "KubeletReady". Empty
	// when the node stated none, or when the token was too long to carry — in
	// which case it is counted in CollectionCoverage.nodes.values_dropped.
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	// When the condition last changed to this status. It is the transition, not
	// the kubelet's heartbeat, which moves every few seconds and is not carried.
	// Absent when the node stated no transition time.
	Since         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCondition) Reset() {
	*x = NodeCondition{}
	mi := &file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCondition) ProtoMessage() {}

func (x *NodeCondition) ProtoReflect() protoreflect.Message {
	mi := &file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCondition.ProtoReflect.Descriptor instead.
func (*NodeCondition) Descriptor() ([]byte, []int) {
	return file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *NodeCondition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NodeCondition) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeCondition) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *NodeCondition) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

// One taint on the node: what it fences off from pods that do not tolerate it.
type NodeTaint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Empty when the taint carries no value; a taint's value is optional.
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// "NoSchedule", "PreferNoSchedule" or "NoExecute".
	Effect        string `protobuf:"bytes,3,opt,name=effect,proto3" json:"effect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeTaint) Reset() {
	*x = NodeTaint{}
	mi := &file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeTaint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeTaint) ProtoMessage() {}

func (x *NodeTaint) ProtoReflect() protoreflect.Message {
	mi := &file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeTaint.ProtoReflect.Descriptor instead.
func (*NodeTaint) Descriptor() ([]byte, []int) {
	return file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *NodeTaint) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *NodeTaint) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *NodeTaint) GetEffect() string {
	if x != nil {
		return x.Effect
	}
	return ""
}

var File_rebuildstack_ingest_kubernetes_v1_node_metadata_proto protoreflect.FileDescriptor

const file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_rawDesc = "" +
	"\n" +
	"5rebuildstack/ingest/kubernetes/v1/node_metadata.proto\x12!rebuildstack.ingest.kubernetes.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a3rebuildstack/ingest/kubernetes/v1/node_device.proto\"\xba\x01\n" +
	"\fNodeMetadata\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12;\n" +
	"\vcaptured_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"capturedAt\x12A\n" +
	"\x05nodes\x18\x04 \x03(\v2+.rebuildstack.ingest.kubernetes.v1.NodeInfoR\x05nodes\"\xd3\n" +
	"\n" +
	"\bNodeInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rinstance_type\x18\x02 \x01(\tR\finstanceType\x12#\n" +
	"\rcapacity_type\x18\x03 \x01(\tR\fcapacityType\x12\x12\n" +
	"\x04zone\x18\x04 \x01(\tR\x04zone\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12%\n" +
	"\x0ekernel_version\x18\x06 \x01(\tR\rkernelVersion\x12\"\n" +
	"\farchitecture\x18\a \x01(\tR\farchitecture\x12'\n" +
	"\x0fkubelet_version\x18\b \x01(\tR\x0ekubeletVersion\x12\x19\n" +
	"\bos_image\x18\t \x01(\tR\aosImage\x12)\n" +
	"\x10operating_system\x18\n" +
	" \x01(\tR\x0foperatingSystem\x12+\n" +
	"\x11container_runtime\x18\v \x01(\tR\x10containerRuntime\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x121\n" +
	"\x12capacity_cpu_milli\x18\r \x01(\x03H\x00R\x10capacityCpuMilli\x88\x01\x01\x127\n" +
	"\x15allocatable_cpu_milli\x18\x0e \x01(\x03H\x01R\x13allocatableCpuMilli\x88\x01\x01\x127\n" +
	"\x15capacity_memory_bytes\x18\x0f \x01(\x03H\x02R\x13capacityMemoryBytes\x88\x01\x01\x12=\n" +
	"\x18allocatable_memory_bytes\x18\x10 \x01(\x03H\x03R\x16allocatableMemoryBytes\x88\x01\x01\x12L\n" +
	" capacity_ephemeral_storage_bytes\x18\x11 \x01(\x03H\x04R\x1dcapacityEphemeralStorageBytes\x88\x01\x01\x12R\n" +
	"#allocatable_ephemeral_storage_bytes\x18\x12 \x01(\x03H\x05R allocatableEphemeralStorageBytes\x88\x01\x01\x12(\n" +
	"\rcapacity_pods\x18\x13 \x01(\x03H\x06R\fcapacityPods\x88\x01\x01\x12.\n" +
	"\x10allocatable_pods\x18\x14 \x01(\x03H\aR\x0fallocatablePods\x88\x01\x01\x12G\n" +
	"\adevices\x18\x15 \x03(\v2-.rebuildstack.ingest.kubernetes.v1.NodeDeviceR\adevices\x12P\n" +
	"\n" +
	"conditions\x18\x16 \x03(\v20.rebuildstack.ingest.kubernetes.v1.NodeConditionR\n" +
	"conditions\x12D\n" +
	"\x06taints\x18\x17 \x03(\v2,.rebuildstack.ingest.kubernetes.v1.NodeTaintR\x06taintsB\x15\n" +
	"\x13_capacity_cpu_milliB\x18\n" +
	"\x16_allocatable_cpu_milliB\x18\n" +
	"\x16_capacity_memory_bytesB\x1b\n" +
	"\x19_allocatable_memory_bytesB#\n" +
	"!_capacity_ephemeral_storage_bytesB&\n" +
	"$_allocatable_ephemeral_storage_bytesB\x10\n" +
	"\x0e_capacity_podsB\x13\n" +
	"\x11_allocatable_pods\"\x85\x01\n" +
	"\rNodeCondition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x120\n" +
	"\x05since\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\"K\n" +
	"\tNodeTaint\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06effect\x18\x03 \x01(\tR\x06effectBOZMgithub.com/RebuildStackCo/runtime-agent/internal/pb/kubernetesv1;kubernetesv1b\x06proto3"

var (
	file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_rawDescOnce sync.Once
	file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_rawDescData []byte
)

func file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_rawDescGZIP() []byte {
	file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_rawDescOnce.Do(func() {
		file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_rawDesc), len(file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_rawDesc)))
	})
	return file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_rawDescData
}

var file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_goTypes = []any{
	(*NodeMetadata)(nil),          // 0: rebuildstack.ingest.kubernetes.v1.NodeMetadata
	(*NodeInfo)(nil),              // 1: rebuildstack.ingest.kubernetes.v1.NodeInfo
	(*NodeCondition)(nil),         // 2: rebuildstack.ingest.kubernetes.v1.NodeCondition
	(*NodeTaint)(nil),             // 3: rebuildstack.ingest.kubernetes.v1.NodeTaint
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*NodeDevice)(nil),            // 5: rebuildstack.ingest.kubernetes.v1.NodeDevice
}
var file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_depIdxs = []int32{
	4, // 0: rebuildstack.ingest.kubernetes.v1.NodeMetadata.captured_at:type_name -> google.protobuf.Timestamp
	1, // 1: rebuildstack.ingest.kubernetes.v1.NodeMetadata.nodes:type_name -> rebuildstack.ingest.kubernetes.v1.NodeInfo
	4, // 2: rebuildstack.ingest.kubernetes.v1.NodeInfo.created_at:type_name -> google.protobuf.Timestamp
	5, // 3: rebuildstack.ingest.kubernetes.v1.NodeInfo.devices:type_name -> rebuildstack.ingest.kubernetes.v1.NodeDevice
	2, // 4: rebuildstack.ingest.kubernetes.v1.NodeInfo.conditions:type_name -> rebuildstack.ingest.kubernetes.v1.NodeCondition
	3, // 5: rebuildstack.ingest.kubernetes.v1.NodeInfo.taints:type_name -> rebuildstack.ingest.kubernetes.v1.NodeTaint
	4, // 6: rebuildstack.ingest.kubernetes.v1.NodeCondition.since:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_init() }
func file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_init() {
	if File_rebuildstack_ingest_kubernetes_v1_node_metadata_proto != nil {
		return
	}
	file_rebuildstack_ingest_kubernetes_v1_node_device_proto_init()
	file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_rawDesc), len(file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_goTypes,
		DependencyIndexes: file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_depIdxs,
		MessageInfos:      file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_msgTypes,
	}.Build()
	File_rebuildstack_ingest_kubernetes_v1_node_metadata_proto = out.File
	file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_goTypes = nil
	file_rebuildstack_ingest_kubernetes_v1_node_metadata_proto_depIdxs = nil
}
