// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: rebuildstack/ingest/kubernetes/v1/node_device.proto

// An extended resource a node advertises, shared by the payloads that describe
// a node and the ones that record its arrival and departure.

package kubernetesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// One extended resource a node advertises, as the node reports it.
//
// Only resources whose name begins with a hardware-vendor prefix are carried.
// Others are counted in CollectionCoverage.nodes.devices_dropped and appear
// nowhere else, so this list is not the node's full set of extended resources.
type NodeDevice struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name, e.g. "nvidia.com/gpu".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// How many the node advertises. Absent means the count was not stated; zero
	// means the node advertises the resource and none of it.
	Capacity *int64 `protobuf:"varint,2,opt,name=capacity,proto3,oneof" json:"capacity,omitempty"`
	// How many the scheduler may still hand out. Absent means the count was not
	// stated; zero means the hardware is on the node and none of it is
	// schedulable.
	Allocatable   *int64 `protobuf:"varint,3,opt,name=allocatable,proto3,oneof" json:"allocatable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeDevice) Reset() {
	*x = NodeDevice{}
	mi := &file_rebuildstack_ingest_kubernetes_v1_node_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDevice) ProtoMessage() {}

func (x *NodeDevice) ProtoReflect() protoreflect.Message {
	mi := &file_rebuildstack_ingest_kubernetes_v1_node_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDevice.ProtoReflect.Descriptor instead.
func (*NodeDevice) Descriptor() ([]byte, []int) {
	return file_rebuildstack_ingest_kubernetes_v1_node_device_proto_rawDescGZIP(), []int{0}
}

func (x *NodeDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeDevice) GetCapacity() int64 {
	if x != nil && x.Capacity != nil {
		return *x.Capacity
	}
	return 0
}

func (x *NodeDevice) GetAllocatable() int64 {
	if x != nil && x.Allocatable != nil {
		return *x.Allocatable
	}
	return 0
}

var File_rebuildstack_ingest_kubernetes_v1_node_device_proto protoreflect.FileDescriptor

const file_rebuildstack_ingest_kubernetes_v1_node_device_proto_rawDesc = "" +
	"\n" +
	"3rebuildstack/ingest/kubernetes/v1/node_device.proto\x12!rebuildstack.ingest.kubernetes.v1\"\x85\x01\n" +
	"\n" +
	"NodeDevice\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\bcapacity\x18\x02 \x01(\x03H\x00R\bcapacity\x88\x01\x01\x12%\n" +
	"\vallocatable\x18\x03 \x01(\x03H\x01R\vallocatable\x88\x01\x01B\v\n" +
	"\t_capacityB\x0e\n" +
	"\f_allocatableBOZMgithub.com/RebuildStackCo/runtime-agent/internal/pb/kubernetesv1;kubernetesv1b\x06proto3"

var (
	file_rebuildstack_ingest_kubernetes_v1_node_device_proto_rawDescOnce sync.Once
	file_rebuildstack_ingest_kubernetes_v1_node_device_proto_rawDescData []byte
)

func file_rebuildstack_ingest_kubernetes_v1_node_device_proto_rawDescGZIP() []byte {
	file_rebuildstack_ingest_kubernetes_v1_node_device_proto_rawDescOnce.Do(func() {
		file_rebuildstack_ingest_kubernetes_v1_node_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rebuildstack_ingest_kubernetes_v1_node_device_proto_rawDesc), len(file_rebuildstack_ingest_kubernetes_v1_node_device_proto_rawDesc)))
	})
	return file_rebuildstack_ingest_kubernetes_v1_node_device_proto_rawDescData
}

var file_rebuildstack_ingest_kubernetes_v1_node_device_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rebuildstack_ingest_kubernetes_v1_node_device_proto_goTypes = []any{
	(*NodeDevice)(nil), // 0: rebuildstack.ingest.kubernetes.v1.NodeDevice
}
var file_rebuildstack_ingest_kubernetes_v1_node_device_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rebuildstack_ingest_kubernetes_v1_node_device_proto_init() }
func file_rebuildstack_ingest_kubernetes_v1_node_device_proto_init() {
	if File_rebuildstack_ingest_kubernetes_v1_node_device_proto != nil {
		return
	}
	file_rebuildstack_ingest_kubernetes_v1_node_device_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rebuildstack_ingest_kubernetes_v1_node_device_proto_rawDesc), len(file_rebuildstack_ingest_kubernetes_v1_node_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rebuildstack_ingest_kubernetes_v1_node_device_proto_goTypes,
		DependencyIndexes: file_rebuildstack_ingest_kubernetes_v1_node_device_proto_depIdxs,
		MessageInfos:      file_rebuildstack_ingest_kubernetes_v1_node_device_proto_msgTypes,
	}.Build()
	File_rebuildstack_ingest_kubernetes_v1_node_device_proto = out.File
	file_rebuildstack_ingest_kubernetes_v1_node_device_proto_goTypes = nil
	file_rebuildstack_ingest_kubernetes_v1_node_device_proto_depIdxs = nil
}
